name: kisanone
description: A smart agriculture app
publish_to: 'none'

environment:
  sdk: ">=2.19.0 <3.0.0"   # ✅ supports your Dart 2.19.2

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  image_picker: ^1.2.0
  http: ^1.5.0
  # firebase_core: ^4.1.0  # Removed for demo mode
  # firebase_auth: ^6.0.2  # Removed for demo mode
  # cloud_firestore: ^6.0.1  # Removed for demo mode
  speech_to_text: ^7.3.0
  geolocator: ^14.0.2
  weather: ^3.2.1
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/kisanone_logo.png